Repository csc510g12/Money-Manager-V3, pull requests merged in 2025-02, with the labels that each got.

#40 added cancel bill split in group
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/main.py
Labels: enhancement

#44 add category selection in group bill split
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/main.py
Labels: enhancement

#50 Bug fix to bill split
  src/bots/telegram/analytics.py
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/main.py
  src/config/config_sample.py
Labels: bug

#51 added docs for group bill split
  README.md
  docs/doc.md
  src/bots/telegram/group_bill_split.py
Labels: documentation

#54 updated docs
  README.md
  docs/doc.md
  src/api/routers/accounts.py
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/main.py
  src/bots/telegram/transfers.py
  tests/api/test_accounts.py
  tests/api/test_categories.py
  tests/api/test_expenses.py
Labels: documentation

#55 added timeout to group bill split
  docs/doc.md
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/main.py
  src/bots/telegram/utils.py
  src/config/config_sample.py
Labels: documentation, enhancement

#56 fix bad reply caused by MarkdownV2 parsing in reply text during process bill split
  src/bots/telegram/group_bill_split.py
Labels: bug

#57 added test bot start
  .coveragerc
  src/bots/telegram/auth.py
  src/bots/telegram/gemini_helper.py
  tests/bots/chat_base.py
  tests/bots/test_account.py
  tests/bots/test_bot_start.py
  tests/bots/test_login.py
  tests/conftest.py
Labels: enhancement

#61 api testing for transfer feature
  src/api/routers/accounts.py
  src/api/routers/users.py
  src/bots/telegram/group_transfer.py
  src/bots/telegram/main.py
  src/bots/telegram/test_group_transfer.py
  src/bots/telegram/transfers.py
  tests/api/test_accounts.py
Labels: enhancement

#62 added group transfer
  src/api/routers/accounts.py
  src/api/routers/users.py
  src/bots/telegram/group_bill_split.py
  src/bots/telegram/group_transfer.py
  src/bots/telegram/main.py
  src/bots/telegram/test_group_transfer.py
  src/config/config_sample.py
Labels: enhancement
